### ISSUE TITLE
'product roadmap'

### ISSUE THREAD

**Issue by spdegabrielle** [racket-tw/sauron#22]
Something like; 

- [x] keyboard shortcuts
- [x] autocomplete
- [x] LaTeX input
- [ ] Scripting functionality like Quickscript in DrRacket (but with event triggers)
- [ ] ...

**Comment by spdegabrielle** [comment]
you might want to use the GitHub wiki functionality for this/

**Comment by dannypsnl** [comment]
I wrote [some](https://github.com/racket-tw/sauron/wiki/Roadmap) to get starting with this.

And I think a QuickSciprt-like functionality might have to wait for a long time, currently, Sauron would focus on `#lang racket` only. Of course, in the future, it should provide a customizable ability to help languages' creators support the new language, and should be simple to add.

I would close this issue since the roadmap page already created.
