### ISSUE TITLE
[Feature] Improve auto-complete

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#43]
Currently, auto-complete can be annoying since it would leave tons of frames on the windows in certain situations.

For example:

![image](https://user-images.githubusercontent.com/22004511/92624099-b115dd00-f2f9-11ea-8d08-5635b1576de5.png)

**Comment by dannypsnl** [comment]
I guess it would also need a lock control just like what REPL did.

**Comment by yjqww6** [comment]
If you want to trigger autocomplete automatically, it is better to avoid autocomplete-mixin and instead implement your own one, because its api is very restricted. 
But if you do want to use it, https://github.com/yjqww6/drcomplete/blob/master/drcomplete-auto/tool.rkt is probably an example. It remembers some positions to avoid re-trigger autocomplete while previous one is still in progress, which seems good enough in practice.

**Comment by dannypsnl** [comment]
Good to know that, would you like to create PR for this?

**Comment by yjqww6** [comment]
For racket programming, currently I am satisfied with drracket, so mostly I wouldn't step in development of other IDEs. But I am glad to see alternatives emerging.

**Comment by dannypsnl** [comment]
Found this happened when typing (`0`-`9`) or `;`, `'`, for now, exclude them can fix the problem, rewrite all would be considered in the future.
